# General variables
ansible_python_interpreter: /usr/bin/python3
ansible_user: sherlock
maintainer: sherlock

# Config network
network_static_ip: "192.168.1.100"
network_gateway: "192.168.1.1"
network_nameservers:
  - "8.8.8.8"
  - "1.1.1.1"

# List of packages to install
default_packages:
  - git
  - curl
  - vim
  - unzip
  - python3-pip
  - net-tools

# Gitea
gitea_version: "1.23.5"
gitea_container_name: "gitea"
gitea_ports:
  - "3000:3000"
  - "222:22"

# Postgres
postgres_version: "17"

# Postgres for Gitea
gitea_db_type: "postgres"
gitea_db_host: "db:5432"
gitea_db_name: "gitea"
gitea_db_user: "gitea"

# Include secrets
gitea_db_password: "{{ lookup('vars', 'gitea_db_password') }}" # in file secrets.yml

# SonarQube
sonarqube_version: "9.9.3-community"

# Postgres for SonarQube
sonarqube_db_user: "sonarqube"
sonarqube_db_password: "{{ lookup('vars', 'sonarqube_db_password') }}"

# Jenkins
jenkins_version: "lts"
jenkins_admin_user: "admin"
jenkins_admin_password: "{{ lookup('vars', 'jenkins_admin_password') }}"




