- name: Copy the file `docker-compose.yml.j2` on the server
  template:
    src: templates/docker-compose.yml.j2
    dest: /opt/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: docker
    mode: "0644"

- name: Check if docker is installed
  command: docker --version
  register: docker_check
  changed_when: false

- name: Start all services with docker compose
  command:
    cmd: docker compose -f /opt/docker-compose.yml up -d
  args:
    chdir: /opt
