- name: Setup DevOps Server
  hosts: devops
  become: yes  # Exécuter en sudo

  pre_tasks:
    - name: Load global variables
      include_vars: ../group_vars/all.yml

    - name: Load secrets
      include_vars:
        file: group_vars/secrets.yml


  roles:
    - common
    - network
    - docker
    - deploy